# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.6)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.20)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget fluid fltk fltk_forms fltk_images fltk_gl)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target fluid
add_executable(fluid IMPORTED)

# Create imported target fltk
add_library(fltk STATIC IMPORTED)

set_target_properties(fltk PROPERTIES
  INTERFACE_LINK_LIBRARIES "/usr/lib/aarch64-linux-gnu/libdl.a;/usr/lib/aarch64-linux-gnu/libX11.so;/usr/lib/aarch64-linux-gnu/libXext.so;/usr/lib/aarch64-linux-gnu/libXinerama.so;/usr/lib/aarch64-linux-gnu/libXfixes.so;/usr/lib/aarch64-linux-gnu/libXcursor.so;/usr/lib/aarch64-linux-gnu/libXrender.so;/usr/lib/aarch64-linux-gnu/libXft.so;/usr/lib/aarch64-linux-gnu/libfontconfig.so"
)

# Create imported target fltk_forms
add_library(fltk_forms STATIC IMPORTED)

set_target_properties(fltk_forms PROPERTIES
  INTERFACE_LINK_LIBRARIES "fltk"
)

# Create imported target fltk_images
add_library(fltk_images STATIC IMPORTED)

set_target_properties(fltk_images PROPERTIES
  INTERFACE_LINK_LIBRARIES "fltk;/usr/lib/aarch64-linux-gnu/libjpeg.so;/usr/lib/aarch64-linux-gnu/libz.so;/usr/lib/aarch64-linux-gnu/libpng.so;/usr/lib/aarch64-linux-gnu/libz.so"
)

# Create imported target fltk_gl
add_library(fltk_gl STATIC IMPORTED)

set_target_properties(fltk_gl PROPERTIES
  INTERFACE_LINK_LIBRARIES "fltk;/usr/lib/aarch64-linux-gnu/libGL.so;/usr/lib/aarch64-linux-gnu/libGLU.so"
)

# Import target "fluid" for configuration "Release"
set_property(TARGET fluid APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(fluid PROPERTIES
  IMPORTED_LOCATION_RELEASE "/data/GitHub/grapa/dep/fltk-1.3.11/build_static/bin/fluid"
  )

# Import target "fltk" for configuration "Release"
set_property(TARGET fltk APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(fltk PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C;CXX"
  IMPORTED_LOCATION_RELEASE "/data/GitHub/grapa/dep/fltk-1.3.11/build_static/lib/libfltk.a"
  )

# Import target "fltk_forms" for configuration "Release"
set_property(TARGET fltk_forms APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(fltk_forms PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/data/GitHub/grapa/dep/fltk-1.3.11/build_static/lib/libfltk_forms.a"
  )

# Import target "fltk_images" for configuration "Release"
set_property(TARGET fltk_images APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(fltk_images PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/data/GitHub/grapa/dep/fltk-1.3.11/build_static/lib/libfltk_images.a"
  )

# Import target "fltk_gl" for configuration "Release"
set_property(TARGET fltk_gl APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(fltk_gl PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/data/GitHub/grapa/dep/fltk-1.3.11/build_static/lib/libfltk_gl.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
