@echo off
echo Reorganizing DBXARCHIVE directory...
echo.

REM Create folder structure
echo Creating folder structure...
mkdir "00_PROJECT_OVERVIEW" 2>nul
mkdir "01_CORE_ARCHITECTURE" 2>nul
mkdir "02_DATABASE_IMPLEMENTATION" 2>nul
mkdir "03_STORAGE_SYSTEMS" 2>nul
mkdir "04_FORMULA_SYSTEM" 2>nul
mkdir "05_SQL_INTEGRATION" 2>nul
mkdir "06_PERFORMANCE_OPTIMIZATION" 2>nul
mkdir "07_TESTING_AND_DEBUGGING" 2>nul
mkdir "08_BUG_INVESTIGATIONS" 2>nul
mkdir "09_LANGUAGE_ENHANCEMENTS" 2>nul
mkdir "10_IMPLEMENTATION_STATUS" 2>nul
mkdir "11_FUTURE_PLANNING" 2>nul
mkdir "12_LEGACY_AND_ARCHIVE" 2>nul

echo Moving files to appropriate folders...

REM 00_PROJECT_OVERVIEW
echo Moving project overview files...
move "ORIGIN_STORY.md" "00_PROJECT_OVERVIEW\" 2>nul
move "GRAPADBX_PROJECT_SUMMARY.md" "00_PROJECT_OVERVIEW\" 2>nul
move "DBXBACKLOG.md" "00_PROJECT_OVERVIEW\" 2>nul
move "DBX_STATUS.md" "00_PROJECT_OVERVIEW\" 2>nul

REM 01_CORE_ARCHITECTURE
echo Moving core architecture files...
move "NEW_GRAPA_DB_DESIGN.md" "01_CORE_ARCHITECTURE\" 2>nul
move "GRAPADBX_DESIGN.md" "01_CORE_ARCHITECTURE\" 2>nul
move "UNIVERSAL_PATH_SYSTEM.md" "01_CORE_ARCHITECTURE\" 2>nul
move "GRAPA_DBX_UNIFIED_PATH_INTEGRATION.md" "01_CORE_ARCHITECTURE\" 2>nul
move "GRAPA_UNIFIED_SYSTEM_ANALYSIS.md" "01_CORE_ARCHITECTURE\" 2>nul

REM 02_DATABASE_IMPLEMENTATION
echo Moving database implementation files...
move "grapadbx_index_implementation.md" "02_DATABASE_IMPLEMENTATION\" 2>nul
move "GRAPA_DBX_INDEX_DESIGN.md" "02_DATABASE_IMPLEMENTATION\" 2>nul
move "GRAPADBX_INDEX_DESIGN_PLAN.md" "02_DATABASE_IMPLEMENTATION\" 2>nul
move "GRAPADBX_INDEX_IMPLEMENTATION_SUMMARY.md" "02_DATABASE_IMPLEMENTATION\" 2>nul
move "GRAPA_DBX_ENHANCED_INDEXING_SYSTEM.md" "02_DATABASE_IMPLEMENTATION\" 2>nul
move "GRAPA_DBX_DICTIONARY_ARCHITECTURE_ANALYSIS.md" "02_DATABASE_IMPLEMENTATION\" 2>nul
move "FIELD_DICTIONARY_IMPLEMENTATION.md" "02_DATABASE_IMPLEMENTATION\" 2>nul

REM 03_STORAGE_SYSTEMS
echo Moving storage systems files...
move "UNIFIED_STORAGE_EXAMPLES.md" "03_STORAGE_SYSTEMS\" 2>nul
move "UNIFIED_STORAGE_PROGRESS.md" "03_STORAGE_SYSTEMS\" 2>nul
move "GRAPA_DBX_TEMPORARY_TRANSACTION_SYSTEM.md" "03_STORAGE_SYSTEMS\" 2>nul
move "GRAPA_DBX_FILE_CACHING_ENHANCEMENTS.md" "03_STORAGE_SYSTEMS\" 2>nul
move "GRAPADBX_MEMORY_MANAGEMENT_FIX.md" "03_STORAGE_SYSTEMS\" 2>nul

REM 04_FORMULA_SYSTEM
echo Moving formula system files...
move "GRAPA_DBX_FORMULA_CALLBACK_IMPLEMENTATION.md" "04_FORMULA_SYSTEM\" 2>nul
move "GRAPA_DBX_FORMULA_FIELDS.md" "04_FORMULA_SYSTEM\" 2>nul
move "GRAPA_FORMULA_EXECUTION_ANALYSIS.md" "04_FORMULA_SYSTEM\" 2>nul
move "GRAPA_DBX_BATCH_FIELD_OPERATIONS.md" "04_FORMULA_SYSTEM\" 2>nul

REM 05_SQL_INTEGRATION
echo Moving SQL integration files...
move "GRAPA_SQL_INTEGRATION.md" "05_SQL_INTEGRATION\" 2>nul
move "GRAPA_DBX_DATABASE_AWARE_COMPARISON.md" "05_SQL_INTEGRATION\" 2>nul

REM 06_PERFORMANCE_OPTIMIZATION
echo Moving performance optimization files...
move "GRAPADBX_PERFORMANCE_ANALYSIS.md" "06_PERFORMANCE_OPTIMIZATION\" 2>nul
move "GRAPA_DBX_CORRECT_PATTERNS.md" "06_PERFORMANCE_OPTIMIZATION\" 2>nul
move "GRAPA_DBX_TESTING_RESULTS.md" "06_PERFORMANCE_OPTIMIZATION\" 2>nul

REM 07_TESTING_AND_DEBUGGING
echo Moving testing and debugging files...
move "GRAPADBX_TESTING_FRAMEWORK.md" "07_TESTING_AND_DEBUGGING\" 2>nul
move "GRAPADBX_DEBUGGING_NOTES.md" "07_TESTING_AND_DEBUGGING\" 2>nul
move "GRAPADBX_DEBUG_OUTPUT_ANALYSIS.md" "07_TESTING_AND_DEBUGGING\" 2>nul
move "DUMP_SYSTEM_IMPLEMENTATION.md" "07_TESTING_AND_DEBUGGING\" 2>nul
move "GRAPA_CLI_COMPREHENSIVE.md" "07_TESTING_AND_DEBUGGING\" 2>nul

REM 08_BUG_INVESTIGATIONS
echo Moving bug investigation files...
move "ROW_TABLE_INDEX_BUG_DEBUG_CONTEXT.md" "08_BUG_INVESTIGATIONS\" 2>nul
move "ROW_TABLE_INDEX_BUG_INVESTIGATION.md" "08_BUG_INVESTIGATIONS\" 2>nul
move "ROW_INDEX_BUG_TODO.md" "08_BUG_INVESTIGATIONS\" 2>nul
move "TABLE_TYPE_ANALYSIS.md" "08_BUG_INVESTIGATIONS\" 2>nul
move "GRAPADBX_FIELD_MODIFICATION_WORKAROUND.md" "08_BUG_INVESTIGATIONS\" 2>nul
move "GRAPADBX_FIELD_DELETION_ANALYSIS.md" "08_BUG_INVESTIGATIONS\" 2>nul
move "GRAPADBX_FIELD_DELETION_INDEX_ANALYSIS.md" "08_BUG_INVESTIGATIONS\" 2>nul
move "GRAPADBX_FIELD_MODIFICATION_DISABLED.md" "08_BUG_INVESTIGATIONS\" 2>nul
move "DOCUMENTATION_SEARCH_BUG.md" "08_BUG_INVESTIGATIONS\" 2>nul

REM 09_LANGUAGE_ENHANCEMENTS
echo Moving language enhancement files...
move "LANGUAGE_SYSTEM_ENHANCEMENTS.md" "09_LANGUAGE_ENHANCEMENTS\" 2>nul
move "GRAPA_WIDGET_IMPLEMENTATION.md" "09_LANGUAGE_ENHANCEMENTS\" 2>nul
move "GRAPA_GROUP_IMPLEMENTATION.md" "09_LANGUAGE_ENHANCEMENTS\" 2>nul
move "GRAPA_RAW_AND_NAMESPACE_ANALYSIS.md" "09_LANGUAGE_ENHANCEMENTS\" 2>nul
move "COMMENT_HANDLING_GUIDE.md" "09_LANGUAGE_ENHANCEMENTS\" 2>nul

REM 10_IMPLEMENTATION_STATUS
echo Moving implementation status files...
move "GRAPA_DBX_IMPLEMENTATION_STATUS.md" "10_IMPLEMENTATION_STATUS\" 2>nul
move "GRAPA_DBX_ACTUAL_STATUS.md" "10_IMPLEMENTATION_STATUS\" 2>nul
move "GRAPADBX_IMPLEMENTATION_NOTES.md" "10_IMPLEMENTATION_STATUS\" 2>nul
move "CURRENT_STATUS.md" "10_IMPLEMENTATION_STATUS\" 2>nul

REM 11_FUTURE_PLANNING
echo Moving future planning files...
move "GRAPADBX_FUTURE_PROOF_DICTIONARY_IMPLEMENTATION.md" "11_FUTURE_PLANNING\" 2>nul
move "CONSOLIDATION_PLAN.md" "11_FUTURE_PLANNING\" 2>nul
move "CLI_FUNCTIONALITY_INVESTIGATION.md" "11_FUTURE_PLANNING\" 2>nul

REM 12_LEGACY_AND_ARCHIVE
echo Moving legacy and archive files...
move "BACKLOG.md" "12_LEGACY_AND_ARCHIVE\" 2>nul
move "CLI_BUG_REPORTS.md" "12_LEGACY_AND_ARCHIVE\" 2>nul
move "AGENT_CONTEXT_LOADING.md" "12_LEGACY_AND_ARCHIVE\" 2>nul

echo.
echo Reorganization complete!
echo.
echo New structure created:
echo - 00_PROJECT_OVERVIEW/     (Project overview and navigation)
echo - 01_CORE_ARCHITECTURE/    (High-level design decisions)
echo - 02_DATABASE_IMPLEMENTATION/ (Core database work)
echo - 03_STORAGE_SYSTEMS/      (Storage and caching improvements)
echo - 04_FORMULA_SYSTEM/       (Formula and field system work)
echo - 05_SQL_INTEGRATION/      (SQL language integration)
echo - 06_PERFORMANCE_OPTIMIZATION/ (Performance studies)
echo - 07_TESTING_AND_DEBUGGING/ (Testing frameworks and debugging)
echo - 08_BUG_INVESTIGATIONS/   (Specific bug analysis)
echo - 09_LANGUAGE_ENHANCEMENTS/ (Language improvements)
echo - 10_IMPLEMENTATION_STATUS/ (Status tracking)
echo - 11_FUTURE_PLANNING/      (Future work and roadmaps)
echo - 12_LEGACY_AND_ARCHIVE/   (Old/duplicate files)
echo.
echo Next steps:
echo 1. Review the new structure
echo 2. Create README.md files for each folder
echo 3. Update cross-references between related topics
echo 4. Remove any duplicate or outdated files
echo.
pause 